### PR TITLE
[DSW] Non mandatory enhancement - add warning message when run dumpwallet or dumpprivkey

### PR DESCRIPTION
**Pull request by LotCooler**
Add a warning message to display on the rpc console the first time the user runs dumpwallet or dumpprivkey.  Successive runs of the command will not trigger the warning message.

### CODE REVIEW

**Comment by bedri** [comment]
@LotCooler 
image

Compilation is giving errors above in dev1 server.

**Comment by LotCooler** [comment]
That's weird.  Is that a memory issue?  It had no issues in jenkins
https://jenkins.4444.tools/job/DSW/job/DSW-develop-AddDumpWalletWarning/

**Comment by LotCooler** [comment]
Oh, it's errorring in a test modoule.  I'm sure jenkins does a configure with  --disable-tests

**Comment by LotCooler** [comment]
It is a test module that is the issue.  The base branch (DSW-develop  or  technically just  "develop" ) also errors with the same error if not configuring with --disable-tests    So the issue looks to me to be in the base branch.

I'll take a look to see what may be happening in the test module, but as of now this PR does not appear to add any new issues not already existing in the base branch.

**Comment by bedri** [comment]
Yes develop branch is also giving error now. It seems the last QT related commit to develop has a bug in test section. We can fix it.

**Comment by LotCooler** [comment]
Added another commit to this PR. The commit only contains comments that were meant to be in there originally but seemed to have been removed. The comments warn about code duplication and changes in one location should be replicated in the other duplicate location.

**Comment by decenomy** [comment]
@LotCooler thank you for your help, your changes were already included on the main develop branch :)

**Pull request closed without merging**
