### PR TITLE
Net - P2P / Update net.cpp

### PR DESCRIPTION
**Pull request by riseup3**
Exclusion for whitelisted nodes added to dupnode condition.

### CODE REVIEW

**Comment by riseup3** [comment]
Certain applications require duplicate ip nodes e.a. gateway, point of services, redundant and high bandwidth applications. An option for whitelisted nodes has been added to the dupnode condition to provide usability under these cirumstances.

**Comment by techy2** [comment]
Please explain why more than one connection on a different port with same IP address would be required for gateway, point of services or redundancy, more bandwidth to any masternode, wallet, seed node or null node.

feel free to DM me on and DSW discord coin channel
techy2

**Comment by riseup3** [comment]
Explanation is already above. You didn't explain why you want to disconnect nodes? Others don't do that. Your dupnode implementaion is preparation for a network attack by separation and denial of nodes and service. Therefore another commit with complete removal of the dupnode condition will follow. Maintainers can also update this commit.

**Comment by techy2** [comment]
testing on dashd main with 7000+ nodes shows a dozen or more clusters of duplicate nodes on a wallet on my system. 100% of those duplicate nodes do not show up as an IP in the masternode list. Consensus of developers involved is that these are phantoms that provide no service to the network, particularly mnb relay service.

These large node networks suffer from repeated unlocks of collateral on masternodes forcing the investors to restart their masternodes and lose the time to the next reward. The cause of the drop is failure of the mnb to propagate throughout the network. This is documented with extensive testing. Dropping duplicate connections increases the mesh connectivity of the network and improves mnb propagation and does no harm to a real node that gets dropped as it is already connected to the node doing the drop and it will have an available outbound (max connections) to seek a connection elsewhere which will again improve the connectivity of the mesh.

If you think otherwise, please provide at least one good reason why 2 connections to/from 2 nodes on the network would be beneficial.

**Comment by crypt0p3t3r** [comment]
Thanks @riseup3 the change is already integrated

**Pull request closed without merging**
